PRODUCT_VENDOR_PROPERTIES +=  \
persist.log.tag.libPowerHal=I \
persist.log.tag.mtkpower@impl=I \
persist.log.tag.mtkpower_client=I \
persist.log.tag.UxUtility=I \
persist.log.tag.PowerHalAddressUitls=I \
persist.log.tag.PowerHalMgrImpl=I \
persist.log.tag.PowerHalMgrServiceImpl=I \
persist.log.tag.PowerHalWifiMonitor=I \
persist.log.tag.RILMUXD=I \
persist.log.tag.DCT=D 